project_name: ctrlscan

before:
  hooks:
    - go mod download

builds:
  - id: ctrlscan
    main: .
    binary: ctrlscan
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - id: default
    builds:
      - ctrlscan
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}Darwin{{ else if eq .Os "linux" }}Linux{{ else if eq .Os "windows" }}Windows{{ else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: ctrlscan
    repository:
      owner: CosmoTheDev
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/CosmoTheDev/ctrlscan-agent"
    description: "AI-powered CVE remediation agent"
    license: "MIT"
    install: |
      bin.install "ctrlscan"
    test: |
      system "#{bin}/ctrlscan", "--help"

scoops:
  - name: ctrlscan
    repository:
      owner: CosmoTheDev
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_BUCKET_GITHUB_TOKEN }}"
    homepage: "https://github.com/CosmoTheDev/ctrlscan-agent"
    description: "AI-powered CVE remediation agent"
    license: "MIT"
