/**
 * Application state — single source of truth for the gateway UI.
 */
export const state = {
  view: "overview",
  status: null,
  jobs: [],
  jobsTotal: 0,
  jobsTotalPages: 1,
  selectedScanJobIds: {},
  jobSummary: null,
  selectedJobId: null,
  selectedJob: null,
  selectedJobCommitHistory: [],
  selectedJobCommitHistoryLookup: null,
  selectedJobScanners: [],
  selectedJobFindings: [],
  selectedJobFindingsTotal: 0,
  selectedJobFindingsTotalPages: 1,
  selectedJobFindingsFacets: { kinds: [], scanners: [], severities: [] },
  selectedJobFindingsSeverityTotals: null,
  selectedJobFixes: [],
  selectedJobRemediationRuns: [],
  selectedJobRemediationRunsTotal: 0,
  selectedJobRemediationRunsPage: 1,
  selectedJobRemediationRunsPageSize: 10,
  selectedJobRemediationRunsTotalPages: 1,
  scanDetailRemediationHistoryCollapsed: false,
  scanDetailRemediationExpandedTaskIds: {},
  pathIgnoreRules: [],
  pathIgnoreRulesLoading: false,
  remediationCampaigns: [],
  remediationSelectedCampaignId: null,
  remediationCampaignTasks: [],
  remediationRepoSuggestions: [],
  remediationRepoSuggestionsLoaded: false,
  remediationRepoSuggestionsLoading: false,
  remediationRepoFilter: "",
  remediationDraft: {
    name: "Offline fix run",
    mode: "triage",
    maxRepos: "10",
    autoPR: false,
    startNow: true,
    selectedRepos: [],
  },
  agentWorkers: [],
  schedules: [],
  agent: null,
  config: null,
  configPath: "",
  events: [],
  es: null,
  liveRefreshTimer: null,
  liveRefreshPending: {
    jobs: false,
    detail: false,
    workers: false,
    remediation: false,
  },
  triggerPlan: {
    targets: [],
    workers: "",
    selectedRepoMap: {},
    forceScan: false,
  },
  triggerPreview: {
    loading: false,
    data: null,
    error: "",
    limit: 10,
    search: "",
  },
  scanDetailFindingsPage: 1,
  scanDetailFindingsPageSize: 25,
  scanDetailFindingsFilters: {
    kind: "",
    scanner: "",
    severity: "",
    title: "",
    path: "",
    q: "",
  },
  scanDetailFindingsDraft: {
    title: "",
    path: "",
    q: "",
  },
  scansPage: 1,
  scansPageSize: 20,
  scansFilters: { repos: [], status: "", minHigh: "", minMedium: "" },
  scansFiltersDraft: { repos: [], status: "", minHigh: "", minMedium: "" },
  scansRepoSuggestions: [],
  scansRepoSuggestionsLoaded: false,
  scansRepoComboSearch: "",
  scansRepoComboOpen: false,
  scansSweepCollapsed: false,
  scansWorkersCollapsed: false,
  scansInlineFindingsPage: 1,
  scansInlineFindingsPageSize: 20,
  scansInlineFindingsSearch: "",
  // Vulnerabilities view
  vulnerabilities: [],
  vulnerabilitiesTotal: 0,
  vulnerabilitiesTotalPages: 1,
  vulnerabilitiesPage: 1,
  vulnerabilitiesPageSize: 50,
  vulnerabilitiesLoading: false,
  vulnerabilitiesFilters: {
    severity: "",
    kind: "",
    scanner: "",
    repo: "",
    q: "",
    status: "open",
    cves: [], // selected CVE/GHSA chips
  },
  vulnerabilitiesFacets: { severities: [], kinds: [], scanners: [], repos: [], cves: [] },
  vulnerabilitiesSeverityTotals: { critical: 0, high: 0, medium: 0, low: 0, fixed: 0 },
  stopBusy: false,
  refreshBusy: false,
  globalLoadingCount: 0,
  globalLoadingMessage: "",
  triggerSubmitBusy: false,
  navPendingView: "",
  scansLoading: false,
  selectedJobLoading: false,
  scansActionBusy: "",
  cronActionBusy: "",
  fixActionBusyKey: "",
  scanDetailAiStopBusy: false,
  scanDetailFixesPage: 1,
  scanDetailFixesPageSize: 10,
  scanDetailFixesSearch: "",
  scanDetailFixesStatus: "",
  scanDetailUiOpenDetails: {},
  sweepUi: {
    skipEventCount: 0,
    latestSummary: null,
  },
  // Heartbeat monitor status from GET /api/agent/health and "agent.health" SSE events.
  agentHealth: null,
};

/**
 * Scan target metadata for trigger modal.
 */
export const targetMeta = {
  own_repos: { label: "Own Repositories", desc: "List repositories you own." },
  watchlist: { label: "Watchlist", desc: "Configured orgs/repos in your ctrlscan watchlist." },
  cve_search: { label: "CVE Search", desc: "Public repository discovery via CVE/security-focused search queries." },
  all_accessible: { label: "All Accessible", desc: "All repos accessible with your token (owner/collab/org)." },
};
