package models

import "time"

// SCAVuln represents a software composition analysis vulnerability finding.
type SCAVuln struct {
	ID                 int64         `json:"id"                   db:"id"`
	UniqueKey          string        `json:"unique_key"           db:"unique_key"`           // provider:owner:repo:branch:package:version
	ScanJobID          int64         `json:"scan_job_id"          db:"scan_job_id"`
	PackageName        string        `json:"package_name"         db:"package_name"`
	VersionAffected    string        `json:"version_affected"     db:"version_affected"`
	VersionRemediation string        `json:"version_remediation"  db:"version_remediation"`
	CVE                string        `json:"cve"                  db:"cve"`
	VulnerabilityID    string        `json:"vulnerability_id"     db:"vulnerability_id"`
	DataSource         string        `json:"data_source"          db:"data_source"`
	Namespace          string        `json:"namespace"            db:"namespace"`
	PackageType        string        `json:"package_type"         db:"package_type"`
	PackageLanguage    string        `json:"package_language"     db:"package_language"`
	Severity           SeverityLevel `json:"severity"             db:"severity"`
	Description        string        `json:"description"          db:"description"`
	PathsFound         string        `json:"paths_found"          db:"paths_found"`           // JSON array
	VulnURLs           string        `json:"vuln_urls"            db:"vuln_urls"`              // JSON array
	References         string        `json:"references"           db:"reference_urls"`         // JSON array
	CVSS               float64       `json:"cvss"                 db:"cvss"`
	CVSSVector         string        `json:"cvss_vector"          db:"cvss_vector"`
	CVSSSource         string        `json:"cvss_source"          db:"cvss_source"`
	EPSS               float64       `json:"epss"                 db:"epss"`
	EPSSPercentile     float64       `json:"epss_percentile"      db:"epss_percentile"`
	EPSSDate           string        `json:"epss_date"            db:"epss_date"`
	CWE                string        `json:"cwe"                  db:"cwe"`
	FixState           string        `json:"fix_state"            db:"fix_state"`
	FixVersions        string        `json:"fix_versions"         db:"fix_versions"`           // JSON array
	CPEs               string        `json:"cpes"                 db:"cpes"`                   // JSON array
	PURL               string        `json:"purl"                 db:"purl"`
	MatchType          string        `json:"match_type"           db:"match_type"`
	Matcher            string        `json:"matcher"              db:"matcher"`
	VersionConstraint  string        `json:"version_constraint"   db:"version_constraint"`
	RelatedVulns       string        `json:"related_vulns"        db:"related_vulns"`          // JSON array
	Status             string        `json:"status"               db:"status"`                 // open|fixed|ignored|pr_open|pr_merged
	PRNumber           int           `json:"pr_number"            db:"pr_number"`
	LastScanned        time.Time     `json:"last_scanned"         db:"last_scanned"`
	FirstSeenAt        time.Time     `json:"first_seen_at"        db:"first_seen_at"`
}

// SBOM represents a software bill of materials generated by syft.
type SBOM struct {
	ID            int64  `json:"id"             db:"id"`
	ScanJobID     int64  `json:"scan_job_id"    db:"scan_job_id"`
	ToolName      string `json:"tool_name"      db:"tool_name"`
	ToolVersion   string `json:"tool_version"   db:"tool_version"`
	ArtifactCount int    `json:"artifact_count" db:"artifact_count"`
}

// SBOMArtifact represents a single package/dependency from an SBOM.
type SBOMArtifact struct {
	ID           int64  `json:"id"            db:"id"`
	SBOMID       int64  `json:"sbom_id"       db:"sbom_id"`
	ScanJobID    int64  `json:"scan_job_id"   db:"scan_job_id"`
	Name         string `json:"name"          db:"name"`
	Version      string `json:"version"       db:"version"`
	ArtifactType string `json:"artifact_type" db:"artifact_type"`
	Language     string `json:"language"      db:"language"`
	Locations    string `json:"locations"     db:"locations"`   // JSON array
	CPEs         string `json:"cpes"          db:"cpes"`        // JSON array
	PURL         string `json:"purl"          db:"purl"`
	Licenses     string `json:"licenses"      db:"licenses"`    // JSON array
	Upstreams    string `json:"upstreams"     db:"upstreams"`   // JSON array
}

// SyftResult mirrors the Syft JSON output schema.
type SyftResult struct {
	Artifacts []struct {
		ID       string `json:"id"`
		Name     string `json:"name"`
		Version  string `json:"version"`
		Type     string `json:"type"`
		Language string `json:"language,omitempty"`
		Locations []struct {
			Path       string `json:"path"`
			AccessPath string `json:"accessPath,omitempty"`
		} `json:"locations,omitempty"`
		Licenses []struct {
			Value          string `json:"value"`
			SPDXExpression string `json:"spdxExpression"`
		} `json:"licenses,omitempty"`
		CPEs CPEs   `json:"cpes,omitempty"`
		PURL string `json:"purl,omitempty"`
	} `json:"artifacts"`
	Schema struct {
		Version string `json:"version"`
		URL     string `json:"url"`
	} `json:"schema"`
}

// GrypeResult mirrors the Grype JSON output schema.
type GrypeResult struct {
	Matches []struct {
		Vulnerability struct {
			ID          string  `json:"id"`
			DataSource  string  `json:"dataSource"`
			Namespace   string  `json:"namespace"`
			Severity    string  `json:"severity"`
			Description string  `json:"description"`
			Cvss        []struct {
				Score  float64 `json:"score"`
				Vector string  `json:"vector"`
				Source string  `json:"source"`
			} `json:"cvss"`
			Epss []struct {
				Score      float64 `json:"score"`
				Percentile float64 `json:"percentile"`
				Date       string  `json:"date"`
			} `json:"epss"`
			URLs []string `json:"urls"`
			CWEs CWEs     `json:"cwes"`
			Fix  struct {
				Versions []string `json:"versions"`
				State    string   `json:"state"`
			} `json:"fix"`
		} `json:"vulnerability"`
		Artifact struct {
			Name      string   `json:"name"`
			Version   string   `json:"version"`
			Type      string   `json:"type"`
			Language  string   `json:"language"`
			CPEs      []string `json:"cpes"`
			PURL      string   `json:"purl"`
			Locations []struct {
				Path string `json:"path"`
			} `json:"locations"`
		} `json:"artifact"`
		RelatedVulnerabilities []struct {
			ID string `json:"id"`
		} `json:"relatedVulnerabilities"`
		MatchDetails []struct {
			Type    string `json:"type"`
			Matcher string `json:"matcher"`
			Found   struct {
				VersionConstraint string `json:"versionConstraint"`
			} `json:"found"`
		} `json:"matchDetails"`
		FixedInVersion string `json:"fixedInVersion"`
	} `json:"matches"`
}

// CPE represents a Common Platform Enumeration entry.
type CPE struct {
	Value  string `json:"cpe"`
	Source string `json:"source,omitempty"`
}

// CPEs is a custom type that handles both CPE-object and plain-string JSON arrays.
type CPEs []CPE

func (c *CPEs) UnmarshalJSON(b []byte) error {
	// Try CPE objects first
	var objects []CPE
	if err := jsonUnmarshal(b, &objects); err == nil {
		*c = objects
		return nil
	}
	// Fall back to plain strings
	var strs []string
	if err := jsonUnmarshal(b, &strs); err != nil {
		return err
	}
	objects = make([]CPE, len(strs))
	for i, s := range strs {
		objects[i] = CPE{Value: s}
	}
	*c = objects
	return nil
}

func (c CPEs) ToStrings() []string {
	out := make([]string, len(c))
	for i, e := range c {
		out[i] = e.Value
	}
	return out
}

// CWE represents a CWE entry from grype. Newer grype releases emit objects
// while older releases may emit plain strings.
type CWE struct {
	ID string `json:"cwe"`
}

// CWEs handles both object and string JSON array formats for vulnerability.cwes.
type CWEs []CWE

func (c *CWEs) UnmarshalJSON(b []byte) error {
	// Newer grype output: [{"cwe":"CWE-79"}]
	var objects []CWE
	if err := jsonUnmarshal(b, &objects); err == nil {
		*c = objects
		return nil
	}

	// Older grype output: ["CWE-79"]
	var strs []string
	if err := jsonUnmarshal(b, &strs); err != nil {
		return err
	}
	objects = make([]CWE, len(strs))
	for i, s := range strs {
		objects[i] = CWE{ID: s}
	}
	*c = objects
	return nil
}

func (c CWEs) ToStrings() []string {
	out := make([]string, len(c))
	for i, e := range c {
		out[i] = e.ID
	}
	return out
}
